### ISSUE TITLE
LLVM ERROR: out of memory

### ISSUE THREAD

**Issue by xxzzddxzd** [HikariObfuscator/Hanabi#1]
Xcode版本10.2，Hanabi版本是最新的release，使用optool注入，未添加-mllvm和其他other c flag
编译报错如下

Applying Apple Clang Hooks...
Applying Apple Clang Hooks...
std::mt19937_64 seeded with current timestamp: 1557301905166
Initializing Hikari Core with Revision ID:9ab2634299fc8e891cf2bc66cd7ca09c59343c48
LLVM ERROR: out of memory
clang: error: unable to execute command: Abort trap: 6
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: arm-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: error: unable to execute command: Abort trap: 6
clang: note: diagnostic msg: Error generating preprocessed source(s).

报错信息如下
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff60dd62c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff60e8bbf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff60d40745 __abort + 144
3   libsystem_c.dylib             	0x00007fff60d406b5 abort + 142
4   clang                         	0x000000010ec74b85 llvm::report_bad_alloc_error(char const*, bool) + 133
5   clang                         	0x000000010ec74bc5 out_of_memory_new_handler() + 21
6   libc++abi.dylib               	0x00007fff5dcf7370 operator new(unsigned long) + 32
7   libLLVMHanabi.dylib           	0x00000001126339e0 llvm::FunctionCallObfuscate::doInitialization(llvm::Module&) + 384
8   libLLVMHanabi.dylib           	0x0000000112658dff llvm::Obfuscation::runOnModule(llvm::Module&) + 127
9   clang                         	0x000000010e7f9057 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 695
10  clang                         	0x000000010ef0d773 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) + 6099
11  clang                         	0x000000010d5c612a clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 458
12  clang                         	0x000000010ddc1a8c clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 44
13  clang                         	0x000000010d408dd6 clang::ParseAST(clang::Sema&, bool, bool) + 294
14  clang                         	0x000000010d407f1a clang::FrontendAction::Execute() + 42
15  clang                         	0x000000010d3e7f2a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 490
16  clang                         	0x000000010d3e61e5 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 693
17  clang                         	0x000000010de5a84a cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1578
18  clang                         	0x000000010d3dbcc1 main + 3105
19  libdyld.dylib                 	0x00007fff60c9b3d5 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00000001171ba5c0  rcx: 0x00007ffee2822b38  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee2822b70  rsp: 0x00007ffee2822b38
   r8: 0x0000000000000000   r9: 0x0000000000989680  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x00000001110b07f0  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff60dd62c6  rfl: 0x0000000000000206  cr2: 0x00007fff93c98260
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by Naville** [comment]
Yeah I don't really have time/interest/hardware to test on Xcode 10.2 ATM

**Comment by Naville** [comment]
另外10.2是LLVM7, 我的Release是LLVM6。 你的版本都对不上，我的文档也写了版本要对应

**Comment by xxzzddxzd** [comment]
hi 想问下，这个LLVM版本不对应的话我自己编译也是不行的，需要等你来更新的吧？

**Comment by Naville** [comment]
首先文档里写了。Xcode版本需要跟llvm版本对应。文档里写了让你去wikipedia查10.2的llvm版本然后用hikari的对应分支。我不知道为什么看文档这么难

**Comment by xxzzddxzd** [comment]
好的 谢谢

**Comment by Naville** [comment]
已经增加10.2的对应版本Release
