### ISSUE TITLE
Issue with theos.

### ISSUE THREAD

**Issue by DanielVolt** [HikariObfuscator/Hanabi#4]
issue resolved.

**Comment by DanielVolt** [comment]
managed to compile but doesn't work with mobilesubstrate on iOS 13. just crashes

**Comment by DanielVolt** [comment]
update: partially works. allobf kills mobilesubstrate with an interesting stack trace; also strcry & funcwra & fco & subobf all kill substrate too. will look into it more

**Comment by meouluxubu** [comment]
Do you solve the problem?

**Comment by ca13ra1** [comment]
@DanielVolt How did you manage to get it working with arm64e support for Velox Reloaded? I seen you were using the function wrapper method. No idea how you managed. Can you elaborate? The dylib dissembled shows [Arm64e](https://imgur.com/hnGkjQe) in IDA Pro.

**Comment by Naville** [comment]
Oooops didn't watch this repo and received absolutely nothing about this repo.

Would love to help if you provide info about the changes you made and obfuscated IR

**Comment by Naville** [comment]
> allobf kills mobilesubstrate with an interesting stack trace; also strcry & funcwra & fco & subobf

FuncWrap is probably to blame in all those cases, elaboration on how and what was killed would help

**Comment by EchoSkill** [comment]
> update: partially works. allobf kills mobilesubstrate with an interesting stack trace; also strcry & funcwra & fco & subobf all kill substrate too. will look into it more

Did you manage to fix it?
