### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by ca13ra1** [HikariObfuscator/Hanabi#6]
**Xcode 11.0 segmentation fault 11 and Xcode 12.0 abort trap 6 substrate tweak**

`Applying Apple Clang Hooks...
Applying Apple Clang Hooks...
std::mt19937_64 seeded with current timestamp: 1601527054986
Initializing Hikari Core with Revision ID:1b02aa842d7c940ddb407569341824788653c263
Loading Symbol Configuration From:/Users/colecabral/Hikari/SymbolConfig.json
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: arm64e-apple-ios10.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/m9/73b1ft490z558l047mjbzwj80000gn/T/Tweak-d08d8d.mm
clang: note: diagnostic msg: /var/folders/m9/73b1ft490z558l047mjbzwj80000gn/T/Tweak-d08d8d.cache
clang: note: diagnostic msg: /var/folders/m9/73b1ft490z558l047mjbzwj80000gn/T/Tweak-d08d8d.sh
clang: note: diagnostic msg: /var/folders/m9/73b1ft490z558l047mjbzwj80000gn/T/Tweak-d08d8d.crash
clang: note: diagnostic msg:`

**Comment by Naville** [comment]
I've already made it pretty clear that any porting/bug fixes was only provided up until Xcode10

**Comment by ca13ra1** [comment]
Is it at all possible to use the LLVM port used in or would that just not work? https://github.com/HikariRebooted/HikariCore
